import express from 'express';
import session from 'express-session';
import multer from 'multer';
import bcrypt from 'bcryptjs';
import sharp from 'sharp';
import archiver from 'archiver';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express();
const PORT=process.env.PORT||3000;
const ROOT=__dirname;
const DATA=path.join(ROOT,'data');
const UP=path.join(DATA,'uploads');
const TH=path.join(DATA,'thumbs');
const DB=path.join(DATA,'db.json');
for(const d of [DATA,UP,TH]) fs.mkdirSync(d,{recursive:true});
if(!fs.existsSync(DB)) fs.writeFileSync(DB,JSON.stringify({clients:[],albums:[],photos:[]},null,2));
const readDB=()=>JSON.parse(fs.readFileSync(DB,'utf8'));
const writeDB=d=>fs.writeFileSync(DB,JSON.stringify(d,null,2));
let db=readDB();
if(!db.clients.length){db.clients.push({id:crypto.randomUUID(),name:'DELUX',slug:'delux',description:'Nightlife / Events',createdAt:Date.now()});writeDB(db)}
const ADMIN_EMAIL=process.env.ADMIN_EMAIL||'admin@vantt.pt';
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'vantt2026';
app.use(express.json());app.use(express.urlencoded({extended:true}));
app.use(session({secret:process.env.SESSION_SECRET||'change-this-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax'}}));
app.use('/assets',express.static(path.join(ROOT,'public')));
app.use('/media',express.static(UP,{maxAge:'7d'}));
app.use('/thumbs',express.static(TH,{maxAge:'7d'}));
const upload=multer({dest:path.join(DATA,'tmp'),limits:{fileSize:50*1024*1024},fileFilter:(req,file,cb)=>/^image\/(jpeg|png|webp)$/.test(file.mimetype)?cb(null,true):cb(new Error('Apenas JPG, PNG e WEBP.'))});
const auth=(req,res,next)=>req.session.admin?next():res.status(401).json({error:'Não autenticado'});
const slugify=s=>s.toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
app.get('/',(req,res)=>res.sendFile(path.join(ROOT,'public','index.html')));
app.post('/api/login',async(req,res)=>{const {email,password}=req.body;if(email!==ADMIN_EMAIL||password!==ADMIN_PASSWORD)return res.status(401).json({error:'Credenciais inválidas'});req.session.admin={email};res.json({ok:true})});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/me',(req,res)=>res.json({authenticated:!!req.session.admin,email:req.session.admin?.email||null}));
app.get('/api/clients',auth,(req,res)=>res.json(db.clients.map(c=>({...c,albums:db.albums.filter(a=>a.clientId===c.id).length}))));
app.post('/api/clients',auth,(req,res)=>{const name=(req.body.name||'').trim();if(!name)return res.status(400).json({error:'Nome obrigatório'});let slug=slugify(name);if(db.clients.some(c=>c.slug===slug))slug+='-'+Date.now();const c={id:crypto.randomUUID(),name,slug,description:req.body.description||'',createdAt:Date.now()};db.clients.push(c);writeDB(db);res.json(c)});
app.get('/api/albums',auth,(req,res)=>{const clientId=req.query.clientId;let a=db.albums.filter(x=>!clientId||x.clientId===clientId);res.json(a.map(x=>({...x,photoCount:db.photos.filter(p=>p.albumId===x.id).length})))});
app.post('/api/albums',auth,(req,res)=>{const client=db.clients.find(c=>c.id===req.body.clientId);const name=(req.body.name||'').trim();if(!client||!name)return res.status(400).json({error:'Cliente e nome são obrigatórios'});let slug=slugify(req.body.slug||name);if(db.albums.some(a=>a.clientId===client.id&&a.slug===slug))slug+='-'+Date.now();const a={id:crypto.randomUUID(),clientId:client.id,name,slug,description:req.body.description||'',eventDate:req.body.eventDate||'',passwordHash:req.body.password?bcrypt.hashSync(req.body.password,10):null,allowDownloads:req.body.allowDownloads!==false,isPublished:req.body.isPublished!==false,createdAt:Date.now()};db.albums.push(a);writeDB(db);res.json(a)});
app.patch('/api/albums/:id',auth,(req,res)=>{const a=db.albums.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({error:'Álbum não encontrado'});Object.assign(a,{name:req.body.name??a.name,description:req.body.description??a.description,eventDate:req.body.eventDate??a.eventDate,allowDownloads:req.body.allowDownloads??a.allowDownloads,isPublished:req.body.isPublished??a.isPublished});if(req.body.password!==undefined)a.passwordHash=req.body.password?bcrypt.hashSync(req.body.password,10):null;writeDB(db);res.json(a)});
app.post('/api/albums/:id/upload',auth,upload.array('photos',500),async(req,res)=>{const a=db.albums.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({error:'Álbum não encontrado'});const added=[];for(const f of req.files||[]){const id=crypto.randomUUID();const ext=f.mimetype==='image/png'?'png':f.mimetype==='image/webp'?'webp':'jpg';const orig=path.join(UP,`${id}.${ext}`),thumb=path.join(TH,`${id}.webp`);fs.renameSync(f.path,orig);const meta=await sharp(orig).rotate().resize({width:900,withoutEnlargement:true}).webp({quality:78}).toFile(thumb);const p={id,albumId:a.id,filename:f.originalname,originalPath:path.basename(orig),thumbPath:path.basename(thumb),width:meta.width,height:meta.height,size:f.size,createdAt:Date.now(),sortOrder:db.photos.filter(x=>x.albumId===a.id).length};db.photos.push(p);added.push(p)}writeDB(db);res.json({count:added.length,photos:added})});
app.get('/api/albums/:id/photos',auth,(req,res)=>res.json(db.photos.filter(p=>p.albumId===req.params.id).sort((a,b)=>a.sortOrder-b.sortOrder)));
app.delete('/api/photos/:id',auth,(req,res)=>{const p=db.photos.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Foto não encontrada'});for(const file of [path.join(UP,p.originalPath),path.join(TH,p.thumbPath)])if(fs.existsSync(file))fs.unlinkSync(file);db.photos=db.photos.filter(x=>x.id!==p.id);writeDB(db);res.json({ok:true})});
app.get('/g/:client/:album',(req,res)=>res.sendFile(path.join(ROOT,'public','gallery.html')));
app.get('/api/public/:client/:album', (req,res)=>{const c=db.clients.find(x=>x.slug===req.params.client);const a=db.albums.find(x=>x.clientId===c?.id&&x.slug===req.params.album);if(!c||!a||!a.isPublished)return res.status(404).json({error:'Galeria não encontrada'});if(a.passwordHash&&!req.session.galleryAccess?.includes(a.id))return res.json({locked:true,client:c,album:{name:a.name,eventDate:a.eventDate,description:a.description}});res.json({locked:false,client:c,album:a,photos:db.photos.filter(p=>p.albumId===a.id).sort((x,y)=>x.sortOrder-y.sortOrder).map(p=>({id:p.id,filename:p.filename,thumb:`/thumbs/${p.thumbPath}`,original:`/media/${p.originalPath}`}))})});
app.post('/api/public/:client/:album/unlock',async(req,res)=>{const c=db.clients.find(x=>x.slug===req.params.client);const a=db.albums.find(x=>x.clientId===c?.id&&x.slug===req.params.album);if(!c||!a)return res.status(404).json({error:'Galeria não encontrada'});if(!a.passwordHash||await bcrypt.compare(req.body.password||'',a.passwordHash)){req.session.galleryAccess=[...(req.session.galleryAccess||[]),a.id];return res.json({ok:true})}res.status(403).json({error:'Password incorreta'})});
app.get('/api/public/:client/:album/download/:photo', (req,res)=>{const c=db.clients.find(x=>x.slug===req.params.client);const a=db.albums.find(x=>x.clientId===c?.id&&x.slug===req.params.album);const p=db.photos.find(x=>x.id===req.params.photo&&x.albumId===a?.id);if(!a||!p||!a.isPublished)return res.status(404).end();if(a.passwordHash&&!req.session.galleryAccess?.includes(a.id))return res.status(403).end();if(!a.allowDownloads)return res.status(403).end();res.download(path.join(UP,p.originalPath),p.filename)});
app.get('/api/public/:client/:album/download-all', (req,res)=>{const c=db.clients.find(x=>x.slug===req.params.client);const a=db.albums.find(x=>x.clientId===c?.id&&x.slug===req.params.album);if(!a||!a.isPublished||!a.allowDownloads)return res.status(404).end();if(a.passwordHash&&!req.session.galleryAccess?.includes(a.id))return res.status(403).end();const photos=db.photos.filter(p=>p.albumId===a.id);res.attachment(`${a.slug}.zip`);const archive=archiver('zip',{zlib:{level:9}});archive.on('error',()=>res.end());archive.pipe(res);for(const p of photos)archive.file(path.join(UP,p.originalPath),{name:p.filename});archive.finalize()});
app.use((err,req,res,next)=>{console.error(err);res.status(400).json({error:err.message||'Erro'});});
app.listen(PORT,()=>console.log(`VANTT Galleries: http://localhost:${PORT}`));
