create extension if not exists pgcrypto;
create table if not exists public.clients(id uuid primary key default gen_random_uuid(),name text not null,created_at timestamptz default now());
create table if not exists public.albums(id uuid primary key default gen_random_uuid(),client_id uuid references public.clients(id) on delete set null,title text not null,slug text unique not null,event_date date,description text,cover_url text,password text,is_public boolean default true,created_at timestamptz default now());
create table if not exists public.photos(id uuid primary key default gen_random_uuid(),album_id uuid references public.albums(id) on delete cascade,storage_path text not null,url text not null,filename text not null,created_at timestamptz default now());
insert into public.clients(name) select 'DELUX' where not exists(select 1 from public.clients where name='DELUX');
alter table public.clients enable row level security;
alter table public.albums enable row level security;
alter table public.photos enable row level security;
drop policy if exists "clients auth" on public.clients;
create policy "clients auth" on public.clients for all to authenticated using(true) with check(true);
drop policy if exists "albums public read" on public.albums;
create policy "albums public read" on public.albums for select to anon,authenticated using(is_public=true);
drop policy if exists "albums auth" on public.albums;
create policy "albums auth" on public.albums for all to authenticated using(true) with check(true);
drop policy if exists "photos public read" on public.photos;
create policy "photos public read" on public.photos for select to anon,authenticated using(exists(select 1 from public.albums a where a.id=album_id and a.is_public=true));
drop policy if exists "photos auth" on public.photos;
create policy "photos auth" on public.photos for all to authenticated using(true) with check(true);
insert into storage.buckets(id,name,public) values('photos','photos',true) on conflict(id) do update set public=true;
drop policy if exists "photo files public read" on storage.objects;
create policy "photo files public read" on storage.objects for select to public using(bucket_id='photos');
drop policy if exists "photo files auth" on storage.objects;
create policy "photo files auth" on storage.objects for all to authenticated using(bucket_id='photos') with check(bucket_id='photos');
create or replace function public.get_public_gallery(p_slug text,p_password text default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare a public.albums; result jsonb;
begin select * into a from public.albums where slug=p_slug and is_public=true limit 1;
if a.id is null then return jsonb_build_object('locked',true);end if;
if a.password is not null and a.password<>coalesce(p_password,'') then return jsonb_build_object('locked',true);end if;
select jsonb_build_object('locked',false,'album',jsonb_build_object('id',a.id,'title',a.title,'slug',a.slug,'event_date',a.event_date,'description',a.description,'cover_url',a.cover_url),'photos',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'url',p.url,'filename',p.filename) order by p.created_at) from public.photos p where p.album_id=a.id),'[]'::jsonb)) into result;return result;end;$$;
grant execute on function public.get_public_gallery(text,text) to anon,authenticated;