import {NextRequest,NextResponse} from "next/server";import {admin} from "@/lib/supabase-admin";import crypto from "crypto";
export const runtime="nodejs";
function ok(req:NextRequest){return req.cookies.get("vantt_admin")?.value==="1"}
export async function GET(req:NextRequest){if(!ok(req))return NextResponse.json({authenticated:false},{status:401});try{const s=admin();const {data:clients,error}=await s.from("clients").select("*").order("created_at",{ascending:false});if(error)throw error;const {data:albums,error:ae}=await s.from("albums").select("*").order("created_at",{ascending:false});if(ae)throw ae;const {data:photos,error:pe}=await s.from("photos").select("id,album_id");if(pe)throw pe;const {data:downloads,error:de}=await s.from("download_events").select("album_id,photo_id,created_at");if(de)throw de;return NextResponse.json({authenticated:true,clients:clients||[],albums:(albums||[]).map(a=>({...a,photoCount:(photos||[]).filter(p=>p.album_id===a.id).length,downloadCount:(downloads||[]).filter(d=>d.album_id===a.id).length}))})}catch(e){const msg=e instanceof Error?e.message:(e&&typeof e==="object"&&"message" in e?String((e as any).message):JSON.stringify(e));return NextResponse.json({error:msg||"Erro interno ao consultar a base de dados"},{status:500})}}
export async function POST(req:NextRequest){const body=await req.json();if(body.action==="login"){if(body.password!==(process.env.ADMIN_PASSWORD||"vantt2026"))return NextResponse.json({error:"Password incorreta"},{status:401});const r=NextResponse.json({ok:true});r.cookies.set("vantt_admin","1",{httpOnly:true,sameSite:"lax",secure:true,path:"/",maxAge:43200});return r}if(body.action==="logout"){const r=NextResponse.json({ok:true});r.cookies.set("vantt_admin","",{httpOnly:true,path:"/",maxAge:0});return r}if(!ok(req))return NextResponse.json({error:"Não autenticado"},{status:401});try{const s=admin();
if(body.action==="client"){const name=String(body.name||"").trim();if(!name)throw Error("Nome do cliente obrigatório");const {data,error}=await s.from("clients").insert({name}).select().single();if(error)throw error;return NextResponse.json(data)}
if(body.action==="album"){const title=String(body.title||"").trim();if(!title||!body.client_id)throw Error("Cliente e nome obrigatórios");const slug=title.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")+"-"+Date.now().toString().slice(-5);const {data,error}=await s.from("albums").insert({client_id:body.client_id,title,slug,event_date:body.event_date||null,description:body.description||"",password:body.password||null,is_public:true}).select().single();if(error)throw error;return NextResponse.json(data)}
if(body.action==="upload-url"){const path="albums/"+body.album_id+"/"+crypto.randomUUID()+"-"+String(body.filename).replace(/[^a-zA-Z0-9._-]/g,"_");const {data,error}=await s.storage.from("photos").createSignedUploadUrl(path,{upsert:false});if(error)throw error;return NextResponse.json({path,token:data.token})}
if(body.action==="photo"){const publicUrl=s.storage.from("photos").getPublicUrl(body.path).data.publicUrl;const {data,error}=await s.from("photos").insert({album_id:body.album_id,storage_path:body.path,url:publicUrl,filename:body.filename}).select().single();if(error)throw error;return NextResponse.json(data)}
return NextResponse.json({error:"Ação inválida"},{status:400})}catch(e){const msg=e instanceof Error?e.message:(e&&typeof e==="object"&&"message" in e?String((e as any).message):JSON.stringify(e));return NextResponse.json({error:msg||"Erro interno"},{status:500})}}